spring.application.name=user-management
server.port=8080

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=userdb

# spring.mongodb.username=admin
# spring.mongodb.password=admin123
# spring.mongodb.authentication-database=userdb

server.forward-headers-strategy=framework